name: clang-tidy
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            clang-tidy \
            cmake \
            jq \
            libglfw3-dev \
            libgl1-mesa-dev \
            libassimp-dev \
            libgtest-dev
      
      - name: Generate compile commands
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -B build

      - name: Check clang-format
        run: |
          { jq -r '.[].file' build/compile_commands.json | grep '\.cpp$'; \
            find include tests -name '*.hpp' ! -path 'include/third_party/*'; } | \
            xargs clang-format --dry-run --Werror
      
      - name: Run clang-tidy
        run: |
          { jq -r '.[].file' build/compile_commands.json | grep '\.cpp$' | \
            xargs clang-tidy -p build \
            --header-filter='^(?!.*/usr/).*$' \
            --warnings-as-errors='*'
